apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-search-k8s
spec:
  selector:
    matchLabels:
      app: spring-search-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-search-k8s
    spec:
      containers:
        - name: spring-search-k8s
          image: neogicel/spring-search:1.0
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 

---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-search-k8s-svc
spec:
  selector:
    app: spring-search-k8s
  ports:
    - protocol: "TCP"
      port: 8082 # The port that the service is running on in the cluster
      targetPort: 8082 # The port exposed by the service
  type: NodePort 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-searchs-k8s-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-search-svc
            port:
              number: 8082
